grin-compiler/grin

- README.md
- grin/default.nix
- nix/free.nix
- nix/llvm-hs-pretty.nix
- nix/llvm-hs-pure.nix
- nix/llvm-hs.nix
- shell.nix
Setup a development environment using nix. Nix expression for grin in the `grin` folder and a shell expression in the root folder with package overrides in the `nix` folder.
> add support for nix

- grin/src/Transformations/Optimising/SimpleDeadFunctionElimination.hs
- grin/test/Transformations/Optimising/SimpleDeadFunctionEliminationSpec.hs
Simple dead function elimination strips unused externals.
> Strip externals

- grin/grin.cabal
- grin/src/AbstractInterpretation/ExtendedSyntax/Sharing/CodeGen.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/Sharing/Pretty.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/Sharing/Result.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/SharingSpec.hs
> Extended syntax: Sharing

- grin/grin.cabal
- grin/src/AbstractInterpretation/ExtendedSyntax/EffectTracking/CodeGen.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/EffectTracking/CodeGenBase.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/EffectTracking/Pretty.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/EffectTracking/Result.hs
- grin/src/Test/ExtendedSyntax/Assertions.hs
- grin/src/Transformations/ExtendedSyntax/Names.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/EffectTrackingSpec.hs
> Extended syntax: Effect Tracking

- grin/grin.cabal
- grin/src/AbstractInterpretation/ExtendedSyntax/LiveVariable/CodeGen.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/LiveVariable/CodeGenBase.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/LiveVariable/Pretty.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/LiveVariable/Result.hs
- grin/src/Test/ExtendedSyntax/Assertions.hs
- grin/src/Test/ExtendedSyntax/Util.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/LiveVariableSpec.hs
> Extended syntax: Live Variable Analysis

- grin/grin.cabal
- grin/src/AbstractInterpretation/ExtendedSyntax/Model.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/OptimiseAbstractProgram.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/IRSpec.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/OptimiseAbstractProgramSpec.hs
> Extended syntax: Abstract Interpretation misc.

- grin/src/AbstractInterpretation/ExtendedSyntax/CreatedBy/CodeGen.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/EffectTracking/CodeGen.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/HeapPointsTo/CodeGen.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/LiveVariable/CodeGen.hs
> Extended syntax: Named alternatives, analyses

- grin/src/AbstractInterpretation/ExtendedSyntax/CreatedBy/CodeGen.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/EffectTracking/CodeGen.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/HeapPointsTo/CodeGen.hs
- grin/src/AbstractInterpretation/ExtendedSyntax/LiveVariable/CodeGen.hs
- grin/src/Grin/ExtendedSyntax/Parse/AST.hs
- grin/src/Grin/ExtendedSyntax/Pretty.hs
- grin/src/Grin/ExtendedSyntax/Syntax.hs
- grin/src/Transformations/ExtendedSyntax/Conversion.hs
- grin/src/Transformations/ExtendedSyntax/Names.hs
- grin/src/Transformations/Optimising/CopyPropagation.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/CreatedBySpec.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/EffectTrackingSpec.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/HptSpec.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/IRSpec.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/LiveVariableSpec.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/OptimiseAbstractProgramSpec.hs
- grin/test/AbstractInterpretation/ExtendedSyntax/SharingSpec.hs
- grin/test/ExtendedSyntax/LintSpec.hs
- grin/test/ExtendedSyntax/ParserSpec.hs
- grin/test/Transformations/ExtendedSyntax/BindNormalisationSpec.hs
- grin/test/Transformations/ExtendedSyntax/MangleNamesSpec.hs
- grin/test/Transformations/ExtendedSyntax/StaticSingleAssignmentSpec.hs
- grin/test/Transformations/Optimising/CopyPropagationSpec.hs
> Extended syntax: Named alternatives, tests

- grin/src/Grin/TypeCheck.hs
A small improvement for the type error if a primitve function has a mismatching type for an argument,
> Improve error reporting.

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/EvaluatedCaseElimination.hs
- grin/src/Transformations/ExtendedSyntax/Optimising/TrivialCaseElimination.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/EvaluatedCaseEliminationSpec.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/TrivialCaseEliminationSpec.hs
> Extended syntax: case eliminating transformations

- grin/app/CLI/Lib.hs
- grin/src/Grin/Lint.hs
- grin/src/Pipeline/Pipeline.hs
- grin/test/Test/EndToEnd.hs
- grin/test/Transformations/ConfluenceSpec.hs
> Add --continue-on-lint option.

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/CSE.hs
- grin/src/Transformations/Optimising/CSE.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/CSESpec.hs
- grin/test/Transformations/Optimising/CSESpec.hs
> Extended syntax: CSE

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/CopyPropagation.hs
- grin/src/Transformations/ExtendedSyntax/Util.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/CopyPropagationSpec.hs
- grin/test/Transformations/Optimising/CopyPropagationSpec.hs
> Extended syntax: copy propagation

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/SparseCaseOptimisation.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/SparseCaseOptimisationSpec.hs
> Extended Syntax: sparse case optimization

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/SimpleDeadFunctionElimination.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/SimpleDeadFunctionEliminationSpec.hs
> Extended Syntax: simple dead function elimination

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/GeneralizedUnboxing.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/GeneralizedUnboxingSpec.hs
> Extended Syntax: generalized unboxing

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/SimpleDeadParameterElimination.hs
- grin/src/Transformations/ExtendedSyntax/Util.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/SimpleDeadParameterEliminationSpec.hs
> Extended Syntax: simple dead parameter elimination

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/SimpleDeadVariableElimination.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/SimpleDeadVariableEliminationSpec.hs
> Extneded Syntax: simple dead variable elimination

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/DeadDataElimination.hs
- grin/test-data/ExtendedSyntax/dead-data-elimination/length_after.grin
- grin/test-data/ExtendedSyntax/dead-data-elimination/length_before.grin
- grin/test-data/ExtendedSyntax/dead-data-elimination/pnode_after.grin
- grin/test-data/ExtendedSyntax/dead-data-elimination/pnode_before.grin
- grin/test/Transformations/ExtendedSyntax/Optimising/CopyPropagationSpec.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/DeadDataEliminationSpec.hs
> Extended Syntax: dead data elimination

- grin/grin.cabal
- grin/src/Transformations/ExtendedSyntax/Optimising/DeadFunctionElimination.hs
- grin/test/Transformations/ExtendedSyntax/Optimising/DeadFunctionEliminationSpec.hs
> Extended Syntax: dead function elimination

- grin/grin.cabal
- grin/src/Pipeline/Eval.hs
- grin/src/Pipeline/Pipeline.hs
- grin/src/Reducer/IO.hs
- grin/src/Reducer/Interpreter/Base.hs
- grin/src/Reducer/Interpreter/Definitional.hs
- grin/src/Reducer/Interpreter/Definitional/Cib.hs
- grin/src/Reducer/Interpreter/Definitional/Instance.hs
- grin/src/Reducer/Interpreter/Definitional/Internal.hs
- grin/src/Reducer/Interpreter/Env.hs
- grin/src/Reducer/Interpreter/Store.hs
- grin/src/Reducer/PrimOps.hs
- grin/src/Reducer/Pure.hs
- grin/test/Reducer/Interpreter/Definitional/CibSpec.hs
> Definitional interpeter framework and Counting Immutable Bean interpreter.

- grin/grin.cabal
> Extended Syntax: GRIN transformations SYNC

- grin/src/Reducer/Pure.hs
> More informative error message for missing primop
