grin/grin/sum_opt_lint_errors.grin
grin/src/AbstractInterpretation/CodeGen.hs
grin/src/Eval.hs
grin/src/Pipeline.hs
grin/src/PrettyLint.hs
grin/src/TypeCheck.hs

Change `codeGen` to use `ExceptT` instead of using `error` and print the
linting errors along with the lint output.

print errors along with lint codeGen use ExceptT

---

grin/default.nix

The .cabal doesn't depend on idris. I'm trying to use grin as a library, and I'm currently compiling idris :) It would be good if this didn't happen

Removed idris from default.nix

---

grin/app/GrinCLI.hs
grin/grin.cabal
grin/prim_ops.c
grin/prim_ops.h
grin/src/Grin/Nametable.hs
grin/src/Grin/Parse/AST.hs
grin/src/Grin/Pretty.hs
grin/src/Grin/PrimOpsPrelude.hs
grin/src/Grin/Syntax.hs
grin/src/Grin/SyntaxDefs.hs
grin/src/Pipeline/Pipeline.hs
grin/src/Reducer/LLVM/Base.hs
grin/src/Reducer/LLVM/CodeGen.hs
grin/src/Reducer/LLVM/PrimOps.hs
grin/src/Reducer/LLVM/TypeGen.hs
grin/src/Reducer/PrimOps.hs
grin/test/ParserSpec.hs
grin/test/PrimOpsSpec.hs
grin/test_prim_ops.c

* FFI support based on prim_ops.c, prim_ops.h
* String primitives must be implemented as FFI calls
* SaveExecutable Pipeline step
* Modified LLVM codegen to handle string types

Ability to create executable.

---

README.md

The install instructions via brew used an incorrect formula name

Fix llvm-7 install instructions for macOS

---

grin/grin.cabal
grin/src/AbstractInterpretation/ExtendedSyntax/BinaryIR.hs
grin/src/AbstractInterpretation/ExtendedSyntax/BinaryResult.hs
grin/src/AbstractInterpretation/ExtendedSyntax/HeapPointsTo/CodeGen.hs
grin/src/AbstractInterpretation/ExtendedSyntax/HeapPointsTo/CodeGenBase.hs
grin/src/AbstractInterpretation/ExtendedSyntax/HeapPointsTo/Pretty.hs
grin/src/AbstractInterpretation/ExtendedSyntax/HeapPointsTo/Result.hs
grin/src/AbstractInterpretation/ExtendedSyntax/IR.hs
grin/src/AbstractInterpretation/ExtendedSyntax/PrettyIR.hs
grin/src/AbstractInterpretation/ExtendedSyntax/Reduce.hs
grin/src/AbstractInterpretation/ExtendedSyntax/ReduceCpp.hs
grin/src/AbstractInterpretation/ExtendedSyntax/Util.hs
grin/src/Grin/ExtendedSyntax/Lint.hs
grin/src/Grin/ExtendedSyntax/PrimOpsPrelude.hs
grin/src/Grin/ExtendedSyntax/TypeCheck.hs
grin/src/Test/ExtendedSyntax/Util.hs
grin/src/Transformations/ExtendedSyntax/Util.hs
grin/test/AbstractInterpretation/ExtendedSyntax/HptSpec.hs
grin/test/ExtendedSyntax/LintSpec.hs
grin/test/ExtendedSyntax/ParserSpec.hs

Modified HPT and the linter such that they correctly handle the new syntax.
For more details see #32.

Extending the syntax of GRIN: HPT

---

grin/src/Grin/ExtendedSyntax/Lint.hs
grin/src/Grin/ExtendedSyntax/Nametable.hs
grin/src/Grin/ExtendedSyntax/Parse/AST.hs
grin/src/Grin/ExtendedSyntax/Pretty.hs
grin/src/Grin/ExtendedSyntax/PrettyLint.hs
grin/src/Grin/ExtendedSyntax/Statistics.hs
grin/src/Grin/ExtendedSyntax/Syntax.hs
grin/src/Transformations/ExtendedSyntax/Conversion.hs
grin/src/Transformations/ExtendedSyntax/Util.hs
grin/test/ExtendedSyntax/ParserSpec.hs

Extended syntax: Named alternatives GRIN directory

---

.travis.yml
grin/src/Reducer/LLVM/JIT.hs

JIT does not support FFI, only a hardwired set of functions.

fix: add __runtime_error to the hardwired JIT FFI

---

grin/src/Transformations/ExtendedSyntax/Conversion.hs
grin/src/Transformations/Optimising/CopyPropagation.hs
grin/src/Transformations/Simplifying/BindingPatternSimplification.hs
grin/test/Transformations/Optimising/CopyPropagationSpec.hs

In this PR, we address some of the problems that arose in #53 regarding the `Old -> New` AST conversion.
See #32.

Extended syntax: syntax conversion fix

---

grin/src/Transformations/Optimising/SimpleDeadParameterElimination.hs
grin/test/Transformations/Optimising/SimpleDeadParameterEliminationSpec.hs

While working on the Idris-Dev test cases, I investigated the optimised code for some simple ones and I found out that we can improve this transformation.
The change should have a smaller memory footprint as its working set only concentrates on the arguments of the function rather than collection of all the variables created/used in the body of the function.

Improve Simple Dead Parameter Elimination.

---

grin/grin.cabal
grin/src/Grin/ExtendedSyntax/Grin.hs
grin/src/Grin/ExtendedSyntax/Parse/AST.hs
grin/src/Test/ExtendedSyntax/New/Test.hs
grin/src/Test/ExtendedSyntax/Util.hs
grin/test/AbstractInterpretation/ExtendedSyntax/CreatedBySpec.hs

Extended syntax: added context-based testing

---

grin/app/CLI/Lib.hs
grin/src/Pipeline/Eval.hs
grin/src/Pipeline/Pipeline.hs
grin/src/Reducer/Base.hs
grin/src/Reducer/IO.hs
grin/src/Reducer/Pure.hs

This is a preliminary for the counting immutable beans implementation.
Motivation: The CIB runtime reuses heap locations after instrumentation of the code. I am going to implement such an evaluator but before that I would like to measure the heap access patterns for the Idris compiled programs. Thus I need this piece of functionality first.

Eval statistics.

---

grin/grin.cabal
grin/src/Transformations/ExtendedSyntax/Optimising/ArityRaising.hs
grin/test/Transformations/ExtendedSyntax/Optimising/ArityRaisingSpec.hs

Extended Syntax: arity raising

---

grin/grin.cabal
grin/src/Transformations/ExtendedSyntax/Optimising/ConstantPropagation.hs
grin/src/Transformations/ExtendedSyntax/Optimising/TrivialCaseElimination.hs
grin/src/Transformations/ExtendedSyntax/Util.hs
grin/test/Transformations/ExtendedSyntax/Optimising/ConstantPropagationSpec.hs

Extended Syntax: constant propagation

---

grin/grin.cabal
grin/src/Transformations/ExtendedSyntax/Optimising/Inlining.hs
grin/test/Transformations/ExtendedSyntax/Optimising/InliningSpec.hs

Extended Syntax: inlining

---

grin/grin.cabal
grin/src/Transformations/ExtendedSyntax/Optimising/CaseHoisting.hs
grin/test/Transformations/ExtendedSyntax/Optimising/CaseHoistingSpec.hs

Extended Syntax: case hoisting

---

grin/grin.cabal
grin/src/Transformations/ExtendedSyntax/Optimising/NonSharedElimination.hs
grin/test/AbstractInterpretation/ExtendedSyntax/SharingSpec.hs
grin/test/Transformations/ExtendedSyntax/Optimising/NonSharedEliminationSpec.hs

Extended Syntax: non-shared elimination

---

grin/src/AbstractInterpretation/ExtendedSyntax/LiveVariable/CodeGen.hs
grin/src/Test/ExtendedSyntax/Util.hs
grin/test-data/ExtendedSyntax/dead-data-elimination/length_after.grin
grin/test-data/ExtendedSyntax/dead-data-elimination/length_before.grin
grin/test-data/ExtendedSyntax/dead-data-elimination/pnode_after.grin
grin/test-data/ExtendedSyntax/dead-data-elimination/pnode_before.grin
grin/test-data/ExtendedSyntax/dead-parameter-elimination/pnode_after.grin
grin/test-data/ExtendedSyntax/dead-parameter-elimination/pnode_before.grin
grin/test/AbstractInterpretation/ExtendedSyntax/LiveVariableSpec.hs

Extended Syntax: LVA fix

---

grin/grin.cabal
grin/src/Transformations/ExtendedSyntax/Optimising/DeadParameterElimination.hs
grin/test/Transformations/ExtendedSyntax/Optimising/DeadParameterEliminationSpec.hs

Extended Syntax: dead parameter elimination

---

.gitignore
grin/src/Grin/ExtendedSyntax/Parse/Basic.hs

The previous `set1` parser would have been able to parse an empty set because it uses `sepBy` instead of `sepBy1`.
It doesn't seem to be used for anything but I think it could be an issue later.
The ignore HIE Yaml is in case anyone uses the Haskell IDE Engine.

Fix set1 parsing and ignore HIE yaml

---

grin/grin.cabal
grin/prim_ops.h
grin/test/ExtendedSyntax/PrimOpsSpec.hs
grin/test/ExtendedSyntax/TestSpec.hs

Extended Syntax: primops tests

---

grin/src/AbstractInterpretation/ExtendedSyntax/Sharing/CodeGen.hs
grin/test/AbstractInterpretation/ExtendedSyntax/SharingSpec.hs
grin/test/Transformations/ExtendedSyntax/Optimising/NonSharedEliminationSpec.hs

Extended Syntax: sharing analysis fix

---

grin/grin.cabal
grin/src/Grin/ExtendedSyntax/Pretty.hs
grin/src/Reducer/ExtendedSyntax/Base.hs
grin/src/Reducer/ExtendedSyntax/IO.hs
grin/src/Reducer/ExtendedSyntax/LLVM/JIT.hs
grin/src/Reducer/ExtendedSyntax/PrimOps.hs
grin/src/Reducer/ExtendedSyntax/Pure.hs
grin/src/Test/ExtendedSyntax/Assertions.hs
grin/test/Reducer/ExtendedSyntax/BaseSpec.hs
grin/test/Reducer/ExtendedSyntax/IOSpec.hs
grin/test/Reducer/ExtendedSyntax/PureSpec.hs

Extended Syntax: reducer

---

grin/grin.cabal
grin/src/Reducer/ExtendedSyntax/LLVM/Base.hs
grin/src/Reducer/ExtendedSyntax/LLVM/CodeGen.hs
grin/src/Reducer/ExtendedSyntax/LLVM/InferType.hs
grin/src/Reducer/ExtendedSyntax/LLVM/PrimOps.hs
grin/src/Reducer/ExtendedSyntax/LLVM/TypeGen.hs

Extended Syntax: reducer LLVM

---

README.md

fixes #113 by removing link to nonexistent file, and replacing with a link to a directory that includes examples of generated code.

Remove link to nonexistent file in README

---

grin/grin.cabal
grin/src/AbstractInterpretation/ExtendedSyntax/CreatedBy/CodeGen.hs
grin/src/Pipeline/ExtendedSyntax/Pipeline.hs
grin/src/Transformations/ExtendedSyntax/Optimising/ArityRaising.hs
grin/src/Transformations/ExtendedSyntax/Optimising/CaseHoisting.hs
grin/src/Transformations/ExtendedSyntax/Optimising/DeadVariableElimination.hs
grin/src/Transformations/ExtendedSyntax/Util.hs
grin/test/AbstractInterpretation/ExtendedSyntax/LiveVariableSpec.hs
grin/test/AbstractInterpretation/ExtendedSyntax/SharingSpec.hs
grin/test/ExtendedSyntax/LintSpec.hs
grin/test/Reducer/ExtendedSyntax/IOSpec.hs
grin/test/Reducer/ExtendedSyntax/PureSpec.hs
grin/test/Samples/ExtendedSyntax/ArityFullRemoveSpec.hs
grin/test/Samples/ExtendedSyntax/SumListSpec.hs
grin/test/Transformations/ExtendedSyntax/Optimising/ArityRaisingSpec.hs
grin/test/Transformations/ExtendedSyntax/Optimising/CaseHoistingSpec.hs
grin/test/Transformations/ExtendedSyntax/Optimising/DeadVariableEliminationSpec.hs

Extended syntax: bugfixes

---

grin/src/Transformations/Optimising/ArityRaising.hs
grin/src/Transformations/Optimising/GeneralizedUnboxing.hs

`grinMain` never has arguments so this makes no difference and these transforms mess with the name, so other optimisations (eg SimpleDeadFunctionElimination) don't work.

Don't arity raise or unbox `grinMain`

---

grin/grin.cabal
grin/src/Reducer/Pure.hs

This allows ffi functions to be run when interpreted

Add libffi support to interpreter

---

grin/src/Grin/ExtendedSyntax/Nametable.hs
grin/src/Grin/ExtendedSyntax/Parse/AST.hs
grin/src/Grin/ExtendedSyntax/Syntax.hs
grin/src/Grin/Nametable.hs
grin/src/Grin/Parse/AST.hs
grin/src/Grin/Syntax.hs
grin/src/Reducer/Pure.hs
grin/src/Transformations/ExtendedSyntax/Conversion.hs
grin/test/ExtendedSyntax/ParserSpec.hs
grin/test/ParserSpec.hs
grin/test/PrettySpec.hs

The syntax is:
```
ffi pure|effectful
<os> "library"
```
eg
```
ffi pure
linux "libc.so.6"
darwin "libc.dylib"
strcpy :: T_String -> T_String -> T_Unit
```
The interpreter also supports this and now does all ffi function loading at the start, rather than when the function is called.

Allow specifying the library an ffi function comes from

---

grin/src/Reducer/Pure.hs

No need to try and use libffi with primops as they are defined in haskell in PureEvalPlugin

Fix ffi linking for primops in interpreter
